CREATE SEQUENCE IF NOT EXISTS default_tag_resource_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS user_resource_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS tag_personal_resource_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS account_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS sheet_seq START WITH 1 INCREMENT BY 50;

