spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.open-in-view=false

# Security
server.servlet.session.cookie.secure=true
auth.secret=${JWT_SECRET}

spring.jpa.show-sql=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration