spring.datasource.url=jdbc:postgresql://localhost:32768/
spring.datasource.username=postgres
spring.datasource.password=postgrespw
spring.jpa.hibernate.ddl-auto=update
auth.secret=THIS-IS-A-LOCAL-JWT-SECRET-NOPRD
server.servlet.session.cookie.secure=false