CREATE TABLE default_tag_resource (
    id_tag UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    blue INTEGER NOT NULL,
    green INTEGER NOT NULL,
    red INTEGER NOT NULL,
    name VARCHAR(255)
);

CREATE TABLE user_resource (
    id_user UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tag_personal_resource (
    id_tag UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    blue INTEGER NOT NULL,
    green INTEGER NOT NULL,
    red INTEGER NOT NULL,
    name VARCHAR(255),
    owner_id_user UUID REFERENCES user_resource (id_user)
);

CREATE TABLE account (
    id_account UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    amount NUMERIC(38,2),
    initial_sold NUMERIC(38,2),
    label VARCHAR(30),
    preview_amount NUMERIC(38,2),
    owner_id_user UUID REFERENCES user_resource (id_user)
);

CREATE TABLE sheet (
    id_sheet UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    account_amount NUMERIC(38,2),
    currency VARCHAR(255),
    date DATE,
    is_income BOOLEAN,
    is_preview BOOLEAN NOT NULL,
    label_sheet VARCHAR(255),
    last_modified TIMESTAMP,
    position INTEGER,
    expenses NUMERIC(38,2),
    account_id_account UUID REFERENCES account (id_account),
    personal_tag_id_tag UUID REFERENCES tag_personal_resource (id_tag),
    tag_id_tag UUID REFERENCES default_tag_resource (id_tag)
);

CREATE TABLE default_tag_resource_linked_transaction (
    default_tag_resource_id_tag UUID NOT NULL REFERENCES default_tag_resource (id_tag),
    linked_transaction_id_sheet UUID NOT NULL UNIQUE REFERENCES sheet (id_sheet),
    PRIMARY KEY (default_tag_resource_id_tag, linked_transaction_id_sheet)
);

CREATE TABLE tag_personal_resource_linked_transaction (
    tag_personal_resource_id_tag UUID NOT NULL REFERENCES tag_personal_resource (id_tag),
    linked_transaction_id_sheet UUID NOT NULL UNIQUE REFERENCES sheet (id_sheet),
    PRIMARY KEY (tag_personal_resource_id_tag, linked_transaction_id_sheet)
);

CREATE TABLE frequency_property_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frequency_type VARCHAR(31) NOT NULL,
    number INTEGER,
    date DATE
);

CREATE TABLE monthly_regular_transaction (
    transaction_id UUID NOT NULL PRIMARY KEY,
    amount DOUBLE PRECISION NOT NULL,
    is_income BOOLEAN NOT NULL,
    label VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    owner_id_user UUID REFERENCES user_resource (id_user),
    personal_tag_id UUID REFERENCES tag_personal_resource (id_tag),
    tag_id UUID REFERENCES default_tag_resource (id_tag),
    frequency_property_id BIGINT REFERENCES frequency_property_entity (id),
    repeat_day INTEGER
);

CREATE TABLE regular_recurring_check_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month INTEGER NOT NULL,
    number_saved_transaction INTEGER NOT NULL,
    year INTEGER NOT NULL,
    id_user UUID REFERENCES user_resource (id_user)
);

CREATE TABLE regular_transaction_tracker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booklet_id UUID NOT NULL,
    last_generated_date DATE NOT NULL,
    regular_transaction_id VARCHAR(255) NOT NULL,
    version BIGINT,
    number_of_generated_transaction INTEGER NOT NULL
);

CREATE TABLE monthly_transaction_booklet (
    transaction_id UUID NOT NULL REFERENCES monthly_regular_transaction (transaction_id),
    id_account UUID NOT NULL REFERENCES account (id_account),
    PRIMARY KEY (transaction_id, id_account)
);
